version: "3.9"
services:
  psql:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    ports:
      - '5432:5432'